### ISSUE TITLE
[TODO] Additional parsers

### ISSUE THREAD

**Issue by loiccoyle** [loiccoyle/hag#4]
- [ ] i3/sway (parsing conf file)
- [ ] awesomewm
- [ ] fzf (man page)
- [ ] firefox: 
  - https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
  - https://firefox-source-docs.mozilla.org/devtools-user/keyboard_shortcuts/index.html
  - https://github.com/bolucat/Firefox/blob/4c28dadf62a9a118368d8ccceaaec0fb9be88dfd/dom/events/ShortcutKeyDefinitions.cpp
  - https://github.com/duckduckgo/zeroclickinfo-goodies/blob/5521881a99e0e912e076cfc50016bfb81a0bcc17/share/goodie/cheat_sheets/json/firefox.json
 - [ ] Chrome
 - [x] inkscape: `/usr/share/inkscape/keys/inkscape.xml`
- [x] gimp
 - [x] bash
